
# html lang
language: en

# header
site_brand_name: Kuo fern lab website 

menu:
  Home: /
  Research: /archives/
  Publications: /publications/
  Members: /members/
  About: /categories/gallery/

# stylesheets loaded in the <head>
stylesheets:
- /css/style.css

# scripts loaded in the end of the body
scripts:
- /js/frame.js

# favicon
favicon: /favicon.ico

date_format: MMM D, YYYY

# profile
profile:
  title: Kuo fern lab website 
  body: We are broadly interested in the evolutionary processes at the gene, genome, and microbiome levels that shaped the plant diversity. We mostly focus on “seed-free” plants (ferns, lycophytes, and bryophytes), and anything that has a weird biology.
  image: /Test_Home.png

  links:
    Publication: /publications/
    Mambers: /members/

# footer
footer:
  copyright_info:
    enable: false
    author:

  powered_by: # Powered by Hexo & Frame
    enable: true

  other_info:
    enable: false
    content:

# color mode: default / classic / dark
color_mode: default

# mathjax setting
# note: need to install the hexo plugin for math: https://github.com/hexojs/hexo-math
mathjax_enable: false
